### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by bluster2005** [webbery/civet#1]
![cat](https://user-images.githubusercontent.com/80499248/111938528-2cf0ad80-8b05-11eb-9660-c045a3ea179d.png)

**Comment by webbery** [comment]
你好，非常感谢你花时间制作了这个可爱的图标。

您提供的这个图标大小是128X128的，但是在程序中要求至少是256X256大小。
对于windows系统，需要ico格式；而对mac系统，需要icns格式。我在进行转换的时候，没有办法把图标进行放大。您能提供一份这样的图标吗？

另外请问这个图标有版权限制吗？

**Comment by bluster2005** [comment]
[cat.zip](https://github.com/webbery/civet/files/6183720/cat.zip)
Free for personal use

**Comment by bluster2005** [comment]
不商用应该没事
