### ISSUE TITLE
安装后只有背景颜色

### ISSUE THREAD

**Issue by 7ic6** [webbery/civet#17]
好想试一下这个软件，但是上次安装什么都不显示，这次有界面了，但没有内容，只有背景色

**Comment by webbery** [comment]
请提供一下界面截图，另外安装路径下有个logs文件，里头的log日志也提供下

**Comment by SamXP2004** [comment]
一样问题。code不能打包
release 版打开就是 空白。

**Comment by 7ic6** [comment]
> 请提供一下界面截图，另外安装路径下有个logs文件，里头的log日志也提供下

![1647012621(1)](https://user-images.githubusercontent.com/66564133/157897689-5b54a88c-9472-4f92-a72a-1776cc8e83e7.jpg)
不知道发生了什么，在安装文件夹里以管理员身份运行civet.exe，居然能用了（中间有在设置启用开发人员模式，但在以管理员身份运行之前依然是空白），另外，一开始只有背景色时，安装文件夹里没有logs文件夹，在出现界面之后才有的logs
![1647013121(1)](https://user-images.githubusercontent.com/66564133/157899159-eb0f77ca-367f-4eda-a243-3a240de30ca8.jpg)
[civet.log](https://github.com/webbery/civet/files/8233339/civet.log)

又试了一下，在配置资源库时，点“完成”没有反应

**Comment by 7ic6** [comment]
> 一样问题。code不能打包 release 版打开就是 空白。

我以管理员身份运行civet.exe之后（在此之前在设置里启用了开发人员模式，不知道有没有联系），有界面了，但是配置资源库时还是有问题，点击“完成”没有反应

**Comment by webbery** [comment]
> 一样问题。code不能打包 release 版打开就是 空白。

code不能打包的原因是否跟这个相同：https://github.com/webbery/civet/runs/5510267474?check_suite_focus=true

**Comment by webbery** [comment]
> > 一样问题。code不能打包 release 版打开就是 空白。
> 
> 我以管理员身份运行civet.exe之后（在此之前在设置里启用了开发人员模式，不知道有没有联系），有界面了，但是配置资源库时还是有问题，点击“完成”没有反应

日志里看你是安装在了C盘，会有写权限的限制，需要开启管理员权限。目前启动的时候会在当前文件夹下创建日志文件，可能还有其他原因。
后面我把创建的文件放到User文件夹里头，就不会有写权限的问题了

**Comment by webbery** [comment]
新的安装包已经修复了这个问题。
我测试了一下，安装在自己的C盘，可以正常启动了。
