### ISSUE TITLE
mac版能安装成功，但是打不开

### ISSUE THREAD

**Issue by badnotes** [webbery/civet#2]
点击打开只是dock栏有个标记，无GUI
右键打开也不行
系统版本 10.15.7

**Comment by webbery** [comment]
你好，我对mac系统还不是太熟。
测试后发现安装包脚本还有些问题，后边会继续改善~
非常感谢反馈

**Comment by webbery** [comment]
进行了一些测试，做了如下更改
1. pkg包卸载不方便，后边修改为dmg包
2. 在mac平台下，入口html文件没有加上file://协议，导致无法打开界面，修改为使用file协议
