### ISSUE TITLE
类型不设置,什么都不显示

### ISSUE THREAD

**Issue by iamqiz** [webbery/civet#22]
不设设置类型, 不应该显示所有类型吗? 
显示是什么都不显示,必须选择至少一个类型, 这就太另类了 
![Snipaste_2022-10-30_17-21-39](https://user-images.githubusercontent.com/48077521/198871415-7c868898-1cb5-4c5c-836f-6cfedefaa9b3.png)

**Comment by webbery** [comment]
这是个bug，在 63dddb21027b8a63dcf9fee6d0e1667778036dcd 提交中修复了

**Comment by webbery** [comment]
这是个bug，在 63dddb21027b8a63dcf9fee6d0e1667778036dcd 提交中修复了
