### ISSUE TITLE
Linux下的编译使用

### ISSUE THREAD

**Issue by Jowisdom** [webbery/civet#3]
如何在ubuntu等主流Linux发行版上使用，求大佬告知

**Comment by webbery** [comment]
这是一个nodejs项目。
你可以在你的Linux上安装上nodejs，nodejs版本建议使用12以上，并确定你的gcc版本支持C++17.
之后你可以下载代码，在代码的根目录下，运行以下几个命令：
```
npm install
npm run build 或者 npm run dev
```
`npm run build`是用来打包项目；`npm run dev`用于调试运行
