### ISSUE TITLE
win版安装后只有后台进程,没有GUI

### ISSUE THREAD

**Issue by gsxgmpkt9020** [webbery/civet#5]
并且重复双击主程序可执行文件后会建立多个重复进程，都是后台无GUI。

另外可以增加个用于提供debug信息的log文件输出吗?

**Comment by webbery** [comment]
软件是先启动后台进程，打开数据库，之后才通知main进程，创建renderer。
如果GUI没起来，可能是后台进程在启动过程抛异常了。

目前数据库操作部分是有log日志的。
后台进程和GUI进程的log文件考虑过添加，不过因为多进程的原因，同时写文件会出现顺序上的混乱，所以有以下三种选择：
1. 最方便的方式是每个进程写一个日志
2. 其次是把其他进程的日志统一放到后台进程去写，同时标明每行对应的进程名
3. 寻找一个支持electron的多进程日志库

第1个选项相比第2个可以调试进程间通信的问题，在日志系统不完善的早期可以先加上；第3个选项我没有找到合适好用的库，当然如果时间充足也可以搞个适配的库

**Comment by hofaeair** [comment]
下个版本会修复吗？蛮想用用看的。

**Comment by webbery** [comment]
> 下个版本会修复吗？蛮想用用看的。

现在已经参考实现了vscode的插件劫持功能，把扩展功能从框架中剥离出来了，也去除了全局的import，减少启动时候加载C++库出现异常的问题  
后边先按每进程一个日志的方式来开发，方便反馈和定位问题  
感谢支持~

**Comment by theblack6688** [comment]
同样问题，期待！

**Comment by webbery** [comment]
当前版本已经添加了日志
