### ISSUE TITLE
mac安装后无图标

### ISSUE THREAD

**Issue by whitewatercn** [webbery/civet#6]
设备：macbook air M1
系统版本：macos big sur 11.2.3
软件版本：Civet-0.1.3-beta

<img width="132" alt="CleanShot 2021-05-23 at 19 15 26@2x" src="https://user-images.githubusercontent.com/58654928/119258191-3d9fcb80-bbfb-11eb-953a-08e8fa8d8175.png">

<img width="244" alt="CleanShot 2021-05-23 at 19 15 51@2x" src="https://user-images.githubusercontent.com/58654928/119258207-4db7ab00-bbfb-11eb-99e1-4c26b01d25d3.png">

大佬加油！

**Comment by webbery** [comment]
上周已经修复了这个问题，下一个发布的版本图标就正常了。

Mac的icns图标需要使用系统自带的工具才能正常生成。
使用其他工具生成的icns图标会有问题。

**Comment by whitewatercn** [comment]
> 上周已经修复了这个问题，下一个发布的版本图标就正常了。
> 
> Mac的icns图标需要使用系统自带的工具才能正常生成。
> 使用其他工具生成的icns图标会有问题。

好的，谢谢啦
