### ISSUE TITLE
这个可以直接在项目中作为一个模块使用吗？

### ISSUE THREAD

**Issue by u19900101** [webbery/civet#7]

**Comment by webbery** [comment]
civet还不是库，所以不能作为一个模块使用

**Comment by u19900101** [comment]
> civet还不是库，所以不能作为一个模块使用

您这个我在本地编译老是报错，不知道怎么解决，能出一个使用的简易教程吗？

**Comment by webbery** [comment]
使用正常的npm install来安装依赖，然后npm run dev就可以跑开发版本，如果需要打包，使用npm run build.
因为搜索的代码是使用C++开发的，使用了C++11的特性。
需要查看一下你的环境，编译器是否支持C++11.
如果还是不行，可以把你的环境和错误信息贴出来

**Comment by webbery** [comment]
新的commit已经在README添加编译说明了
